name: test

on:
    # push:
    #   branches:
    #     - master
    #     - main
    # pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "26.0.2"
                  gleam-version: "0.32.2"
                  rebar3-version: "3"
                  # elixir-version: "1.15.4"
            - run: gleam format --check src test
            - run: gleam deps download
            - run: gleam test
