name: vlib modules CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-module-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build V
        run: make
      - name: Build module documentation
        run: ./v doc -m -f html vlib/
      - name: Deploy docs to vercel
        if: ${{ github.event_name == 'push' }}
        run: npx vercel --confirm --prod --name vmodules --token ${{ secrets.VERCEL_TOKEN }} vlib/_docs/ || true
